menus/urls.py
from django.conf.urls import url


from .views import (

    ItemCreateView,
    ItemListView,
    ItemDetailView,
    ItemUpdateView,
)
urlpatterns = [
  
    url(r'^create/$',ItemCreateView.as_view(), name='create' ),#  restaurant_createview
    #url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(),name='update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(),name='detail'),
    url(r'^$', ItemListView.as_view(),name='list'),
  

]

muypicky/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from restaurants.views import RestaurantCreateView,RestaurantListView, RestaurantDetailView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, LogoutView

from menus.views import HomeView
from profiles.views import ProfileFollowToggle, RegisterView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',HomeView.as_view(),name ='home'),
    url(r'^restaurants/',include('restaurants.urls',namespace='restaurants') ),
    url(r'^u/',include('profiles.urls',namespace='profiles') ),
    url(r'^menus/',include('menus.urls',namespace='menus') ),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name= 'password_reset'),
    url(r'^password_reset/done/$', PasswordResetView.as_view(), name= 'password_reset_done'),
    url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$',TemplateView.as_view(template_name='contact.html'), name='contact'),
]

restaurants/urls.py
from django.conf.urls import url
from django.contrib import admin
from restaurants.views import RestaurantCreateView ,RestaurantListView, RestaurantDetailView, RestaurantUpdateView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


urlpatterns = [

    url(r'^create/$',RestaurantCreateView.as_view(), name='create' ),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(),name='detail'),
    url(r'^$', RestaurantListView.as_view(),name='list'),
    

]

restaurants/models.py
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from .validators import validate_category
from django.core.urlresolvers import reverse
# Create your models here.


User = settings.AUTH_USER_MODEL

class RestaurantLocationQuerySet(models.query.QuerySet):
    def search(self,query):

        if query:
            query.strip()
            return self.filter(
            Q(name__icontains=query)     | 
            Q(location__icontains=query) |
            Q(category__icontains=query) |
            Q(location__icontains=query) |
            Q(item__name__icontains=query)|
            Q(item__contents__icontains=query) ).distinct()
        return self




#Model Manager
class RestaurantLocationManager(models.Manager):

    def get_queryset(self):
        return RestaurantLocationQuerySet(self.model, using= self._db)


    def search(self,query):
        return self.get_queryset().search(query)


class RestaurantLocation(models.Model):

    
    owner       =    models.ForeignKey(User)
    name        =    models.CharField(max_length=120)
    location    =    models.CharField(max_length=120, null = True, blank = True)
    category    =    models.CharField(max_length=120, null=True, blank=True, validators=[validate_category])
    timestamp   =    models.DateTimeField(auto_now_add=True)
    updated     =    models.DateTimeField(auto_now=True)
    slug        =    models.SlugField(null=True, blank=True)

    objects = RestaurantLocationManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('restaurants:detail', kwargs={'slug':self.slug})

    @property
    def title(self):
        return self.name

def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    #print('saving..')
    #print(instance.timestamp)
    instance.category = instance.category.capitalize()
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
        

"""def rl_post_save_receiver(sender, instance, *args, **kwargs):
    print('saved..')
    print(instance.timestamp)
"""
#Signals
pre_save.connect(rl_pre_save_receiver, sender=RestaurantLocation)
#post_save.connect(rl_post_save_receiver, sender=RestaurantLocation)

restaurants/forms.py
from django import forms
from .models import RestaurantLocation
from .validators import validate_category

class RestaurantCreateForm(forms.Form):
    name        =    forms.CharField()
    location    =    forms.CharField(required = False)
    category    =    forms.CharField(required = False)

    #clean_ functions are called when form.is_valid() is invoked
    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name == 'Hello':
            raise forms.ValidationError("Error")
        return name


class RestaurantLocationCreateForm(forms.ModelForm):
    #category = forms.CharField(required = False,validators= [validate_category])
    class Meta:
            model = RestaurantLocation
            fields = [
                'name',
                'location',
                'category',
                'slug'
            ]
    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name == 'Hello':
            raise forms.ValidationError("Error")
        return name
    
    def clean_email(self):
        name = self.cleaned_data.get("name")
        if name == 'Hello':
            raise forms.ValidationError("Error")
        return name

restaurants/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
import random
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView,CreateView, UpdateView
from .forms import RestaurantCreateForm, RestaurantLocationCreateForm
from .models import RestaurantLocation

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


### Filter by Restaurant Category
class RestaurantListView(LoginRequiredMixin,ListView):
    template_name = 'restaurants/restaurants_list.html'
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

class RestaurantDetailView(LoginRequiredMixin,DetailView):
    template_name = 'restaurants/restaurants_detail.html'
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)


class RestaurantCreateView(LoginRequiredMixin,CreateView):
    form_class = RestaurantLocationCreateForm
    template_name = 'form.html'
    sucess_url = '/restaurants/'

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

    def form_valid(self,form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(RestaurantCreateView,self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantCreateView,self).get_context_data(*args, **kwargs)
        context['title']='Add Restaurant'
        return context

class RestaurantUpdateView(LoginRequiredMixin,UpdateView):
    form_class = RestaurantLocationCreateForm
    template_name = 'restaurants/detail-update.html'
    #sucess_url = '/restaurants/'
    
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

    def form_valid(self,form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(RestaurantUpdateView,self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantUpdateView,self).get_context_data(*args, **kwargs)
        name = self.get_object().name
        context['title']=f'Update Restaurant: {name}'
        return context

restaurants/templates/restaurants/detail-update.html
{% extends "base.html" %}

{% block head_title%} {{ form.instance.title }}| Restaurants || {{block.super}}{% endblock head_title %}


{% block content %}

    <h1> {{ form.instance.name}} <small>{{ form.instance.category }} </small></h1>
    <p>{{form.instance.location }} </p>
    <p> {{ form.instance.timestamp }}, Updated {{form.instance.updated|timesince }} ago </p>

    <h3> Make Changes</h3>
    {% include 'snippets/form-snippet.html' with form=form %}

{% endblock %}

restaurants/templates/restaurants/form.html
{% extends "base.html" %}

{% block head_title%}Add Restaurant || {{block.super}}{% endblock head_title %}


{% block content %}

    <h1> Add Restaurant</h1>

{% if form.errors %}
{{ form.errors }}

{% endif %}
    <form method='POST'> {% csrf_token %}

       <!--  <input type='text' name='name' placeholder="Your title"/><br/>
        <input type='text' name='location' placeholder="Location"/><br/>
        <input type='text' name='category' placeholder="Category"/><br/> -->

         {{ form.as_p }}
        <button type='submmit'>Save</button>
        

    </form>  


{% endblock %}

restaurants/templates/restaurants/restaurants_detail.html
{% extends "base.html" %}

{% block head_title%}Restaurants || {{block.super}}{% endblock head_title %}


{% block content %}

    <h1> {{ object.name}} <small>{{ object.category }} </small></h1>


    <p>{{ object.location }} </p>
    <p> {{ object.timestamp }}, Updated {{ object.updated|timesince }} ago </p>


{% endblock %}

restaurants/templates/restaurants/restaurants_list.html
{% extends "base.html" %}

{% block head_title%}Restaurants || {{block.super}}{% endblock head_title %}


{% block content %}
<h1> Restaurant List<small><a href='{% url "restaurants:create" %}'> Add </a></small></h1>
    <div class='row'>
        <div class='col-sm-12'>
            <div class='thumbnail'>
                <ul>
                        {% for obj in object_list %}                                
                            <li style='margin-bottom: 15px;'>
                                <a href='{{ obj.get_absolute_url }}'>{{ obj }}</a> <br/>                            
                                {{ obj.name }} {{ obj.category }} {{ obj.location }} {{ obj.name }} {{ obj.timestamp }} {{ obj.updated }} 
                            </li>
                            {% empty %}
                                <li><a href='{% url "restaurants:create"%}'> Add One</a></li>
                        {% endfor %}                
                </ul>
            </div>
        </div>
    </div>
{% endblock %}