menus/urls.py
from django.conf.urls import url


from .views import (

    ItemCreateView,
    ItemListView,
    ItemDetailView,
    ItemUpdateView,
)
urlpatterns = [
  
    url(r'^create/$',ItemCreateView.as_view(), name='create' ),#  restaurant_createview
    #url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(),name='update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(),name='detail'),
    url(r'^$', ItemListView.as_view(),name='list'),
  

]

muypicky/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from restaurants.views import RestaurantCreateView,RestaurantListView, RestaurantDetailView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, LogoutView

from menus.views import HomeView
from profiles.views import ProfileFollowToggle, RegisterView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',HomeView.as_view(),name ='home'),
    url(r'^restaurants/',include('restaurants.urls',namespace='restaurants') ),
    url(r'^u/',include('profiles.urls',namespace='profiles') ),
    url(r'^menus/',include('menus.urls',namespace='menus') ),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name= 'password_reset'),
    url(r'^password_reset/done/$', PasswordResetView.as_view(), name= 'password_reset_done'),
    url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$',TemplateView.as_view(template_name='contact.html'), name='contact'),
]

templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

templates/snippets/form-snippet.html
    {% if form.errors %}
    {{ form.errors }}

    {% endif %}
    <form method='POST'> {% csrf_token %}

       <!--  <input type='text' name='name' placeholder="Your title"/><br/>
        <input type='text' name='location' placeholder="Location"/><br/>
        <input type='text' name='category' placeholder="Category"/><br/> -->

         {{ form.as_p }}
        <button type='submmit'>Save</button>
        

    </form>  

templates/snippets/js.html
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script
src="https://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
crossorigin="anonymous"></script>

templates/snippets/nav.html
<div class='container'>
        <h1>Muy Picky</h1>
        <a href='{% url "home" %}'>Home</a>
        <a href='{% url "about" %}'>About</a>
        <a href='{% url "contact" %}'>Contact</a>
        
        {% if request.user.is_authenticated %}
                <a href='{% url "restaurants:list" %}'>Restaurants</a>
                <a href='{% url "menus:list" %}'>Items</a>

        {% endif %}
</div>

templates/snippets/sidebar.html
<ul>
        <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
    <li>Item 4</li>

</ul>