menus/urls.py
from django.conf.urls import url


from .views import (

    ItemCreateView,
    ItemListView,
    ItemDetailView,
    ItemUpdateView,
)
urlpatterns = [
  
    url(r'^create/$',ItemCreateView.as_view(), name='create' ),#  restaurant_createview
    #url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(),name='update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(),name='detail'),
    url(r'^$', ItemListView.as_view(),name='list'),
  

]

muypicky/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from restaurants.views import RestaurantCreateView,RestaurantListView, RestaurantDetailView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, LogoutView

from menus.views import HomeView
from profiles.views import ProfileFollowToggle, RegisterView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',HomeView.as_view(),name ='home'),
    url(r'^restaurants/',include('restaurants.urls',namespace='restaurants') ),
    url(r'^u/',include('profiles.urls',namespace='profiles') ),
    url(r'^menus/',include('menus.urls',namespace='menus') ),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name= 'password_reset'),
    url(r'^password_reset/done/$', PasswordResetView.as_view(), name= 'password_reset_done'),
    url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$',TemplateView.as_view(template_name='contact.html'), name='contact'),
]

menus/models.py
from django.db import models
from django.conf import settings
# Create your models here.
from restaurants.models import RestaurantLocation
from django.core.urlresolvers import reverse

class Item(models.Model):
    #associations
    user         = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant   = models.ForeignKey(RestaurantLocation)

    #Item stuff
    name         = models.CharField(max_length=120)
    contents     = models.TextField(help_text='Separate each item by comma')
    excludes     = models.TextField(blank=True, null= True, help_text='Separate each item by comma')
    public       = models.BooleanField(default=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    updated      = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk':self.pk})


    class Meta:
        ordering =['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

menus/forms.py
from django import forms
from .models import Item
from restaurants.models import RestaurantLocation

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields =[
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public'
        ]
    def __init__(self, user=None,*args, **kwargs):
        print(user)
        #print(kwargs.pop('instance'))
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)#.exclude(item__isnull=False)

menus/views.py
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView
from .forms import ItemForm
from .models import Item
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class HomeView(View):
    def get(self,request, *args, **kwars):
        if not request.user.is_authenticated():
           return render(request, "home.html", {})
        
        user = request.user
        is_following_user_ids = [x.user.id for x in user.is_following.all()]
        qs  = Item.objects.filter(user__id__in=is_following_user_ids, public=True)
        return render(request, "menus/home-feed.html", {'object_list': qs})
    

class ItemListView(LoginRequiredMixin,ListView):

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemDetailView(LoginRequiredMixin,DetailView):

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemCreateView(LoginRequiredMixin,CreateView):
    template_name = 'menus/detail-update.html'
    form_class = ItemForm
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def form_valid(self,form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView,self).form_valid(form)

     #Override get_context_data function#
    def get_context_data(self, *args, **kwargs):
        context = super(ItemCreateView,self).get_context_data(*args, **kwargs)
        context['title']='Add Menu Item'
        return context
    #Override get_form_kwargs function#
    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        #kwargs['instance'] = Item.objects.filter(user = self.request.user).first()
        return kwargs



class ItemUpdateView(LoginRequiredMixin,UpdateView):
    template_name = 'menus/detail-update.html'
    form_class = ItemForm


    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)



     #Override get_context_data function#
    def get_context_data(self, *args, **kwargs):
        context = super(ItemUpdateView,self).get_context_data(*args, **kwargs)
        name = self.get_object().name
        context['title']=f'Update Item: {name}'
        return context
    #Override get_form_kwargs function#
    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        #kwargs['instance'] = Item.objects.filter(user = self.request.user).first()
        return kwargs

menus/templates/menus/detail-update.html
{% extends "base.html" %}


{% block content %}

    <h1> {{ form.instance.name }}</h1>
    <h2> {{ form.instance.restaurant.name }}</h2>
    <p> Location: {{ form.instance.restaurant.location }}</p>


        {% for item in form.instance.get_contents %}
                <li>{{ item }}</li>
                {% endfor %}
 
             {% if form.instance.excludes %}
             Contents
             <ul>
             {% for item in form.instance.get_excludes %}
                        <li>{{ item }}</li>
                        {% endfor %}
             </ul>
             {% endif %}
        
             <hr/>
        <h3> Make Changes</h3>
             {% include 'snippets/form-snippet.html' with form=form %}


{% endblock %}

menus/templates/menus/form.html
{% extends "base.html" %}

{% block head_title%}Add Restaurant || {{block.super}}{% endblock head_title %}


{% block content %}

    <h1> {{ title }}</h1>

{% if form.errors %}
{{ form.errors }}

{% endif %}
    <form method='POST'> {% csrf_token %}

       <!--  <input type='text' name='name' placeholder="Your title"/><br/>
        <input type='text' name='location' placeholder="Location"/><br/>
        <input type='text' name='category' placeholder="Category"/><br/> -->

         {{ form.as_p }}
        <button type='submmit'>Save</button>
        

    </form>  


{% endblock %}

menus/templates/menus/home-feed.html
{% extends "base.html" %}
{% block content %}
<h1>User Following Feed</h1>
    {% for obj in object_list %}{% csrf_token %}

    <div class='row'>
        <div class='col-sm-6 text-center col-sm-offset-3'>
            <div class='thumbnail'>
            <h3><a href='{% url "profiles:detail" username=obj.user.username %}'>{{ obj.user }}</a></h3> 
            <h4>{{ obj.name }}</h4> 
            <p> <a href='{% url "profiles:detail" username=obj.user.username %}?q={{ obj.restaurant.title }}' >{{ obj.restaurant.title }}  </a>| <a href='{% url "profiles:detail" username=obj.user.username %}?q={{ obj.restaurant.category }}'>{{ obj.restaurant.category }}</a></p>
        <ul>
            
             {% for item in obj.restaurant.item_set.all %} 
                     <b style='margin-bottom: 15px;'>{{ item.name }}</b> with

                       {% for ing in item.get_contents %}
                            <a href='{% url "profiles:detail" username=obj.user.username  %}?q={{ ing }}'><span class='badge badge-default'>{{ ing }}</span></a>
                       {% endfor %}
        </br>
           {% endfor %} 
                   
        </ul>
    </div>
</div>

    </div>   

    {% endfor %}

{% endblock %}

menus/templates/menus/item_detail.html
{% extends "base.html" %}


{% block content %}

    <h1> {{ object.name }}</h1>
    <h2> {{ object.restaurant.name }}</h2>
    <p> Location: {{ object.restaurant.location }}</p>


        {% for item in object.get_contents %}
                <li>{{ item }}</li>
                {% endfor %}
 
             {% if object.excludes %}
             Contents
             <ul>
             {% for item in object.get_excludes %}
                        <li>{{ item }}</li>
                        {% endfor %}
             </ul>
             {% endif %}



{% endblock %}

menus/templates/menus/item_list.html
{% extends "base.html" %}


{% block content %}


    <h1> Menu Items <small><a href='{% url "menus:create" %}'>Add</a></small></h1> 

    {% for obj in object_list %}
    <div class='row'>
        <div class='col-sm-6 text-center col-sm-offset-3'>
            <div class='thumbnail'>
             <b style='margin-bottom: 15px;'><a href='{{ obj.get_absolute_url }}'>{{ obj.name }}</a></b>
             {% if obj.contents %}
             <h5>Contents</h5>
             <ul>
                    {% for item in obj.get_contents %}
                        <li class='badge badge-default'>{{ item }}</li>
                        {% endfor %}
             </ul>
             {% endif %}
             {% if obj.excludes %}
             Contents
             <ul>
                    {% for item in obj.get_excludes %}
                        <li>{{ item }}</li>
                        {% endfor %}
             </ul>
             {% endif %}
            </div>
            </div>
        </div>

    {% endfor %}

{% endblock %}